# Fichier de configuration Codemagic pour un projet Capacitor iOS Webview
# Placez ce fichier à la racine de votre dépôt Git.

workflows:
  ios-build-webview:
    name: Capacitor iOS Webview Build
    max_build_duration: 60

    # 1. Environnement de Construction
    instance_type: mac_mini_m1 
    environment:
      vars:
        XCODE_SCHEME: "App"
        APP_ID: "com.tbso.society"
        
      xcode: latest
      cocoapods: default
      node: 20

    # 2. Dépendances et Préparation (Bloc scripts)
    scripts:
      - name: Install Node dependencies
        script: npm install
          
      - name: Add iOS platform and generate assets
        script: |
          # Ajoute la plateforme iOS (recrée le dossier ios/)
          npx capacitor add ios
          
          # Regénère les icônes et splash screens
          npx capacitor-assets generate
          
          # Synchronise la configuration web avec le projet natif
          npx capacitor sync ios
          
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          
      # 3. Compilation iOS (Utilisation de la commande xcode-project build-ipa)
      - name: Build iOS App
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release" \
            --export-method "app-store" # Utiliser "app-store" pour TestFlight/App Store

    # 4. Configuration de la Signature Apple (Bloc publishing)
    # Ce bloc doit être au même niveau que 'scripts'
    publishing:
      ios_user_and_team_secrets: 
        certificate_and_profile_matching: true
        
      # Publication par e-mail (syntaxe corrigée)
      email:
        recipients:
          - votre.email@example.com
        triggering:
          - success
          - failure
      
      # Intégration App Store Connect (syntaxe corrigée)
      app_store_connect:
        # Laissez vide si vous ne soumettez pas automatiquement
        # Si vous soumettez, vous devez configurer l'API Key dans l'interface Codemagic
        # et décommenter les lignes suivantes :
        # auth:
        #   api_key: App Store Connect API Key
        # submit_to_testflight: true
