# Fichier de configuration Codemagic pour un projet Capacitor iOS Webview
# Placez ce fichier à la racine de votre dépôt Git.

workflows:
  ios-build-webview:
    name: Capacitor iOS Webview Build
    max_build_duration: 60

    # 1. Environnement de Construction
    instance_type: mac_mini_m1 
    environment:
      vars:
        XCODE_SCHEME: "App"
        APP_ID: "com.tbso.society"
        
      xcode: latest
      cocoapods: default
      node: 20

    # 2. Dépendances et Préparation
    scripts:
      - name: Install Node dependencies
        script: npm install
          
      - name: Add iOS platform and generate assets
        script: |
          npx capacitor add ios
          npx capacitor-assets generate
          npx capacitor sync ios
          
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          
      # 3. Compilation iOS
      - name: Build iOS App
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release" \
            --export-method "app-store"
