# Fichier de configuration Codemagic pour un projet Capacitor iOS Webview
# Placez ce fichier à la racine de votre dépôt Git.

workflows:
  ios-build-webview:
    name: Capacitor iOS Webview Build
    max_build_duration: 60

    # 1. Environnement de Construction
    instance_type: mac_mini_m1 
    environment:
      # Les variables de signature sont gérées par Codemagic via l'interface
      # et sont injectées automatiquement.
      vars:
        XCODE_SCHEME: "App"
        APP_ID: "com.tbso.society"
        
      xcode: latest
      cocoapods: default
      node: 20

    # 2. Dépendances et Préparation
    scripts:
      - name: Install Node dependencies
        script: npm install
          
      - name: Add iOS platform and generate assets
        script: |
          npx capacitor add ios
          npx capacitor-assets generate
          npx capacitor sync ios
          
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          
      # 3. Compilation iOS
      - name: Build iOS App
        script: |
          # La compilation utilise les variables de signature injectées par Codemagic
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release" \
            --export-method "app-store"

    # 4. Publication (Minimaliste et Stable)
    publishing:
      # Signature Apple : Indique à Codemagic d'utiliser les certificats configurés
      # dans l'interface utilisateur.
      ios_user_and_team_secrets:
        certificate_and_profile_matching: true
        
      # Publication par e-mail (syntaxe la plus simple et la plus stable)
      email:
        recipients:
          - society@tbso.com
        triggering:
          - success
          - failure
